#!/usr/bin/env python

from launch import LaunchDescription
from launch_ros.actions import Node
from launch.substitutions import LaunchConfiguration
from launch.actions import DeclareLaunchArgument


def generate_launch_description():
    return LaunchDescription([
       
        DeclareLaunchArgument('input_cloud_topic', default_value='/livox/lidar',
                              description='Input point cloud topic'),
        DeclareLaunchArgument('resolution', default_value='0.1',
                              description='Octomap resolution'),
        DeclareLaunchArgument('frame_id', default_value='map',
                              description='Frame ID for the octomap'),
        DeclareLaunchArgument('base_frame_id', default_value='base_link',
                              description='Base frame ID for the octomap'),
        DeclareLaunchArgument('use_height_map', default_value='false',
                              description='Use height map'),
        DeclareLaunchArgument('colored_map', default_value='false',
                              description='Use colored map'),
        DeclareLaunchArgument('color_factor', default_value='1.0',
                              description='Color factor for the octomap'),
        DeclareLaunchArgument('filter_ground_plane', default_value='false',
                              description='Enable ground filtering'),
        DeclareLaunchArgument('filter_speckles', default_value='false',
                              description='Enable speckle filtering'),
        DeclareLaunchArgument('ground_filter/distance', default_value='0.1',
                              description='Ground filter distance threshold'),
        DeclareLaunchArgument('ground_filter/angle', default_value='0.1',
                              description='Ground filter angle threshold'),
        DeclareLaunchArgument('ground_filter/plane_distance', default_value='0.05',
                              description='Ground filter plane distance threshold'),
        DeclareLaunchArgument('compress_map', default_value='true',
                              description='Enable map compression'),
        DeclareLaunchArgument('incremental_2D_projection', default_value='true',
                              description='Enable incremental 2D projection'),
        DeclareLaunchArgument('sensor_model/max_range', default_value='10.0',
                              description='Sensor model maximum range'),
        DeclareLaunchArgument('sensor_model/hit', default_value='0.7',
                              description='Sensor model hit probability'),
        DeclareLaunchArgument('sensor_model/miss', default_value='0.4',
                              description='Sensor model miss probability'),
        DeclareLaunchArgument('sensor_model/min', default_value='0.12',
                              description='Sensor model minimum probability'),
        DeclareLaunchArgument('sensor_model/max', default_value='0.97',
                              description='Sensor model maximum probability'),
        DeclareLaunchArgument('color/r', default_value='255',
                              description='Color red component'),
        DeclareLaunchArgument('color/g', default_value='0',
                              description='Color green component'),
        DeclareLaunchArgument('color/b', default_value='0',
                              description='Color blue component'),
        DeclareLaunchArgument('color/a', default_value='255',
                              description='Color alpha component'),
        DeclareLaunchArgument('color_free/r', default_value='200',
                              description='Free space color red component'),
        DeclareLaunchArgument('color_free/g', default_value='200',
                              description='Free space color green component'),
        DeclareLaunchArgument('color_free/b', default_value='200',
                              description='Free space color blue component'),
        DeclareLaunchArgument('color_free/a', default_value='255',
                              description='Free space color alpha component'),
        DeclareLaunchArgument('publish_free_space', default_value='true',
                              description='Publish free space in the octomap'),
        DeclareLaunchArgument('point_cloud_max_x', default_value='10.0',
                              description='Maximum X coordinate for point cloud'),
        DeclareLaunchArgument('point_cloud_max_y', default_value='10.0',
                              description='Maximum Y coordinate for point cloud'),
        DeclareLaunchArgument('point_cloud_max_z', default_value='2.0',
                              description='Maximum Z coordinate for point cloud'),
        DeclareLaunchArgument('point_cloud_min_x', default_value='-10.0',
                              description='Minimum X coordinate for point cloud'),
        DeclareLaunchArgument('point_cloud_min_y', default_value='-10.0',
                              description='Minimum Y coordinate for point cloud'),
        DeclareLaunchArgument('point_cloud_min_z', default_value='0.1',
                              description='Minimum Z coordinate for point cloud'),
        DeclareLaunchArgument('occupancy_min_z', default_value='0.1',
                              description='Minimum Z coordinate for occupancy'),
        DeclareLaunchArgument('occupancy_max_z', default_value='2.0',
                              description='Maximum Z coordinate for occupancy'),
        DeclareLaunchArgument('latch', default_value='false',
                              description='Latch the topic for parameter events'),
        DeclareLaunchArgument('octomap_path', default_value='/home/gjh/octomap.bt',
                              description='Path to save the octomap file'),
        # DeclareLaunchArgument('max_depth', default_value='10.0',
        #                       description='Maximum depth for the octomap'),
        DeclareLaunchArgument('min_x_size', default_value='1.0',
                              description='Minimum X size for the octomap'),
        DeclareLaunchArgument('min_y_size', default_value='1.0',
                              description='Minimum Y size for the octomap'),

        Node(
            package='octomap_server',
            executable='octomap_server_node',
            output='screen',
            remappings=[('cloud_in', LaunchConfiguration('input_cloud_topic'))],
            parameters=[{'resolution': LaunchConfiguration('resolution'),
                         'frame_id': LaunchConfiguration('frame_id'),
                         'base_frame_id': LaunchConfiguration('base_frame_id'),
                         'use_height_map': LaunchConfiguration('use_height_map'),
                         'colored_map': LaunchConfiguration('colored_map'),
                         'color_factor': LaunchConfiguration('color_factor'),
                         'filter_ground_plane': LaunchConfiguration('filter_ground_plane'),
                         'filter_speckles': LaunchConfiguration('filter_speckles'),
                         'ground_filter/distance': LaunchConfiguration('ground_filter/distance'),
                         'ground_filter/angle': LaunchConfiguration('ground_filter/angle'),
                         'ground_filter/plane_distance': LaunchConfiguration('ground_filter/plane_distance'),
                         'compress_map': LaunchConfiguration('compress_map'),
                         'incremental_2D_projection': LaunchConfiguration('incremental_2D_projection'),
                         'sensor_model/max_range': LaunchConfiguration('sensor_model/max_range'),
                         'sensor_model/hit': LaunchConfiguration('sensor_model/hit'),
                         'sensor_model/miss': LaunchConfiguration('sensor_model/miss'),
                         'sensor_model/min': LaunchConfiguration('sensor_model/min'),
                         'sensor_model/max': LaunchConfiguration('sensor_model/max'),
                         'color/r': LaunchConfiguration('color/r'),
                         'color/g': LaunchConfiguration('color/g'),
                         'color/b': LaunchConfiguration('color/b'),
                         'color/a': LaunchConfiguration('color/a'),
                         'color_free/r': LaunchConfiguration('color_free/r'),
                         'color_free/g': LaunchConfiguration('color_free/g'),
                         'color_free/b': LaunchConfiguration('color_free/b'),
                         'color_free/a': LaunchConfiguration('color_free/a'),
                         'publish_free_space': LaunchConfiguration('publish_free_space'),
                         'use_sim_time': True,
                         'point_cloud_max_x': LaunchConfiguration('point_cloud_max_x'),
                         'point_cloud_max_y': LaunchConfiguration('point_cloud_max_y'),
                         'point_cloud_max_z': LaunchConfiguration('point_cloud_max_z'),
                         'point_cloud_min_x': LaunchConfiguration('point_cloud_min_x'),
                         'point_cloud_min_y': LaunchConfiguration('point_cloud_min_y'),
                         'point_cloud_min_z': LaunchConfiguration('point_cloud_min_z'),
                         'occupancy_min_z': LaunchConfiguration('occupancy_min_z'),
                         'occupancy_max_z': LaunchConfiguration('occupancy_max_z'),
                         'latch': LaunchConfiguration('latch'),
                        #  'octomap_path': LaunchConfiguration('octomap_path'),
                        #  'max_depth': LaunchConfiguration('max_depth'),
                         'min_x_size': LaunchConfiguration('min_x_size'),
                         'min_y_size': LaunchConfiguration('min_y_size'),
                         }]
        )
    ])